"""SHD — Input-Layer Perturbation (perturbation-aware training).

Reproduces the original Beyond Rate SHD experiment. For each perturbation
level f, the train/val/test splits are regenerated by relocating a fraction f
of each input neuron's spikes to random empty time bins (per-neuron spike
counts are preserved, so the rate code survives and only spike timing is
destroyed). A fresh model is trained on each perturbed dataset and evaluated
on the correspondingly perturbed test set.

Architecture: Input -> 128 hidden -> 128 hidden -> 20 output (SRMALPHA)
Dataset variants: whole (700 input neurons), part (224), norm (224)

The USE_DELAY flag selects training with learnable delays (SGD-delay) or
without (SGD).
"""

import os
import json
import random
from typing import Optional

import numpy as np
from scipy.io import loadmat
import torch
from torch import nn
from tqdm import tqdm

import slayerSNN as snn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Resolve all file paths relative to this script's location, not the CWD.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


# =====================================================================
# Global configuration
# =====================================================================

# Batch mode: when True, the main run trains EVERY combination of
# (dataset_key, use_delay) listed in ALL_VARIATIONS case-by-case.
# When False, only the single (DATASET_KEY, USE_DELAY) pair below is run.
TRAIN_ALL_VARIATION: bool = True

# Network variant: True for SGD-delay, False for SGD (no delay).
# Ignored when TRAIN_ALL_VARIATION is True.
USE_DELAY: bool = True

# Dataset variant: "whole", "part", or "norm".
# Ignored when TRAIN_ALL_VARIATION is True.
DATASET_KEY: str = "whole"

# All (dataset_key, use_delay) pairs to iterate over in batch mode.
ALL_VARIATIONS: list[tuple[str, bool]] = [
    (dataset, delay)
    for dataset in ("norm", "part", "whole")
    for delay in (False, True)
]

DATASET_CONFIGS = {
    "whole": {"mat_file": "shd_data/shd_whole.mat", "input_dim": 700},
    "part":  {"mat_file": "shd_data/shd_part_new.mat", "input_dim": 224},
    "norm":  {"mat_file": "shd_data/shd_norm_new.mat", "input_dim": 224},
}

# SLAYER neuron and simulation descriptors
SIM_PARAMS = {"Ts": 1, "tSample": 200}
LIF_PARAMS = {
    "type": "SRMALPHA",
    "theta": 10,
    "tauSr": 1,
    "tauRho": 0.1,
    "tauRef": 2,
    "scaleRef": 2,
    "scaleRho": 0.1,
}

# Data split ratios
TRAIN_RANGE = (0.0, 0.6)
VAL_RANGE = (0.6, 0.75)
TEST_RANGE = (0.75, 0.9)

# Training hyper-parameters
HIDDEN_UNITS: int = 128
NUM_CLASSES: int = 20
EPOCHS: int = 1000
BATCH_SIZE: int = 128
LEARNING_RATE: float = 0.1
SEED: int = 42
MAX_DELAY: int = 64
EARLY_STOP_PATIENCE: int = 300

# Input-perturbation sweep
F_VALUES: list[float] = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]

# Default input dim for the single-variation case. Every other per-variation
# name is derived inside run_variation_sweep so batch mode cannot have one
# variation overwrite another's checkpoints or logs.
INPUT_DIM: int = DATASET_CONFIGS[DATASET_KEY]["input_dim"]


# =====================================================================
# Load SHD dataset
# =====================================================================

def load_shd_data(mat_path: str, target_T: int = 200) -> tuple[np.ndarray, np.ndarray]:
    """Load SHD dataset from a .mat file and pad the time dimension.

    Args:
        mat_path: Path to the .mat file containing 'X' and 'Y'.
        target_T: Target time dimension (zero-pad if shorter).

    Returns:
        Tuple of (X, Y) where X has shape (N, neurons, target_T).
    """
    data = loadmat(mat_path)
    X = data["X"]
    Y = data["Y"].ravel()

    n_samples, n_neurons, T = X.shape
    if T < target_T:
        padded = np.zeros((n_samples, n_neurons, target_T), dtype=X.dtype)
        padded[:, :, :T] = X
        X = padded
        print(f"Padded time dimension from {T} to {target_T}")

    print(f"Loaded {mat_path}: X={X.shape}, Y={Y.shape}, classes={len(np.unique(Y))}")
    return X, Y


# =====================================================================
# Input-layer spike perturbation
# =====================================================================

def partial_randomize_spike_train(
    spike_train: np.ndarray,
    f: float = 0.0,
    max_attempts: int = 50,
) -> np.ndarray:
    """Randomly relocate a fraction *f* of each neuron's spikes.

    Args:
        spike_train: Binary array of shape (num_neurons, T).
        f: Fraction of spikes to relocate (0 = no change, 1 = full shuffle).
        max_attempts: Max tries to find an empty time bin per spike.

    Returns:
        Perturbed spike train with the same shape and per-neuron spike counts.
    """
    if f <= 0:
        return spike_train

    num_neurons, T = spike_train.shape
    new_train = np.copy(spike_train)

    for neuron_idx in range(num_neurons):
        spike_times = np.where(spike_train[neuron_idx] == 1)[0]
        for old_time in spike_times:
            if np.random.rand() < f:
                new_train[neuron_idx, old_time] = 0
                inserted = False
                attempts = 0
                while not inserted and attempts < max_attempts:
                    attempts += 1
                    new_t = np.random.randint(0, T)
                    if new_train[neuron_idx, new_t] == 0:
                        new_train[neuron_idx, new_t] = 1
                        inserted = True
    return new_train


def preprocess_full_dataset(
    X: np.ndarray,
    Y: np.ndarray,
    f: float,
    training_range: tuple[float, float] = TRAIN_RANGE,
    validation_range: tuple[float, float] = VAL_RANGE,
    testing_range: tuple[float, float] = TEST_RANGE,
    seed: int = 42,
) -> tuple:
    """Split the dataset and perturb the input spikes of every split at level f.

    Args:
        X: Spike trains of shape (N, num_neurons, T).
        Y: Integer labels of shape (N,).
        f: Perturbation fraction applied to all splits.
        training_range: Fractional (start, end) of the training split.
        validation_range: Fractional (start, end) of the validation split.
        testing_range: Fractional (start, end) of the test split.
        seed: Seed for the split shuffle and the perturbation RNG.

    Returns:
        Tuple of ((X_train, Y_train), (X_val, Y_val), (X_test, Y_test)).
    """
    np.random.seed(seed)

    N = len(Y)
    train_idx = np.arange(int(N * training_range[0]), int(N * training_range[1]))
    val_idx = np.arange(int(N * validation_range[0]), int(N * validation_range[1]))
    test_idx = np.arange(int(N * testing_range[0]), int(N * testing_range[1]))

    np.random.shuffle(train_idx)

    def _process(indices: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        X_out = np.array([partial_randomize_spike_train(X[i], f) for i in indices])
        return X_out, Y[indices]

    return _process(train_idx), _process(val_idx), _process(test_idx)


# =====================================================================
# Network architecture
# =====================================================================

class SHDNetwork(nn.Module):
    """2-hidden-layer SLAYER SNN for SHD classification."""

    def __init__(
        self,
        input_dim: int,
        hidden_units: int = 128,
        num_classes: int = 20,
        use_delay: bool = True,
        max_delay: int = 64,
    ):
        super().__init__()
        slayer = snn.layer(LIF_PARAMS, SIM_PARAMS)
        self.slayer = slayer
        self.use_delay = use_delay
        self.max_delay = max_delay

        self.fc1 = nn.utils.weight_norm(
            slayer.dense(input_dim, hidden_units), name="weight"
        )
        self.fc2 = nn.utils.weight_norm(
            slayer.dense(hidden_units, hidden_units), name="weight"
        )
        self.fc3 = nn.utils.weight_norm(
            slayer.dense(hidden_units, num_classes), name="weight"
        )

        if use_delay:
            self.delay1 = slayer.delay(hidden_units)
            self.delay2 = slayer.delay(hidden_units)

    def _prepare_input(self, x: torch.Tensor) -> torch.Tensor:
        """Ensure the input is a 5-D NCHWT tensor on the correct device."""
        if isinstance(x, np.ndarray):
            x = torch.from_numpy(x)
        if x.dim() == 3:
            x = x.unsqueeze(2).unsqueeze(3)
        return x.float().to(device)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Run the forward pass.

        Perturbation is baked into the data upstream, so this is a plain
        forward pass with no perturbation hook.
        """
        x = self._prepare_input(x)
        x = self.slayer.spike(self.fc1(self.slayer.psp(x)))
        if self.use_delay:
            x = self.delay1(x)
        x = self.slayer.spike(self.fc2(self.slayer.psp(x)))
        if self.use_delay:
            x = self.delay2(x)
        x = self.slayer.spike(self.fc3(self.slayer.psp(x)))
        return x

    def clamp_delays(self, max1: int = 64, max2: int = 64) -> None:
        """Clamp the two delay layers into [0, max1] and [0, max2]."""
        if not self.use_delay:
            return
        self.delay1.delay.data.clamp_(0, max1)
        self.delay2.delay.data.clamp_(0, max2)

    def get_delays(self) -> dict[str, np.ndarray]:
        """Return the current delay values of each delay layer."""
        delays: dict[str, np.ndarray] = {}
        if self.use_delay:
            delays["delay1"] = self.delay1.delay.data.cpu().numpy()
            delays["delay2"] = self.delay2.delay.data.cpu().numpy()
        return delays


# =====================================================================
# Training loop
# =====================================================================

def set_seed(seed: int) -> None:
    """Set random seeds for reproducibility."""
    import torch.backends.cudnn as cudnn
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        cudnn.benchmark = False
        cudnn.deterministic = True
        cudnn.enabled = False


def build_loss_and_optimizer(net: SHDNetwork, lr: float = 0.1) -> tuple:
    """Build the NumSpikes loss, Nadam optimizer, and LR scheduler.

    Args:
        net: Network whose parameters the optimizer updates.
        lr: Initial learning rate.

    Returns:
        Tuple of (loss_fn, optimizer, scheduler).
    """
    error_cfg = {
        "neuron": LIF_PARAMS,
        "simulation": SIM_PARAMS,
        "training": {
            "error": {
                "type": "NumSpikes",
                "tgtSpikeRegion": {"start": 0, "stop": 200},
                "tgtSpikeCount": {True: 40, False: 4},
            }
        },
    }
    loss_fn = snn.spikeLoss.spikeLoss(error_cfg)
    optimizer = snn.utils.optim.Nadam(net.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.MultiStepLR(
        optimizer, milestones=[300], gamma=0.1
    )
    return loss_fn, optimizer, scheduler


def train_model(
    X_train: np.ndarray,
    Y_train: np.ndarray,
    X_val: np.ndarray,
    Y_val: np.ndarray,
    input_dim: int,
    hidden_units: int = 128,
    num_classes: int = 20,
    use_delay: bool = True,
    max_delay: int = 64,
    epochs: int = 1000,
    batch_size: int = 128,
    lr: float = 0.1,
    seed: int = 42,
    patience: int = 300,
) -> tuple[SHDNetwork, dict]:
    """Train an SHDNetwork on already-perturbed training data.

    Args:
        X_train: Perturbed training spike trains, shape (N, neurons, T).
        Y_train: Training labels.
        X_val: Perturbed validation spike trains.
        Y_val: Validation labels.
        input_dim: Number of input neurons.
        hidden_units: Units in each hidden layer.
        num_classes: Number of output classes.
        use_delay: Whether to train learnable delays.
        max_delay: Initial delay clamp bound.
        epochs: Maximum number of epochs.
        batch_size: Mini-batch size.
        lr: Initial learning rate.
        seed: Seed applied before model construction.
        patience: Early-stopping patience in epochs.

    Returns:
        Tuple of (best model by validation loss, per-epoch training log).
    """
    set_seed(seed)

    net = SHDNetwork(
        input_dim, hidden_units, num_classes, use_delay, max_delay
    ).to(device)
    loss_fn, optimizer, scheduler = build_loss_and_optimizer(net, lr=lr)
    loss_fn = loss_fn.to(device)

    best_val_loss = float("inf")
    best_model_state: Optional[dict] = None
    early_stop_counter = 0

    # Adaptive delay clamping state
    update1 = 0
    update2 = 0
    thea1 = max_delay
    thea2 = max_delay

    log = {
        "epoch": [],
        "train_loss": [],
        "val_loss": [],
        "val_acc": [],
        "delay_mean": [],
    }

    n_train = len(Y_train)
    total_steps = epochs * max(1, n_train // batch_size)
    with tqdm(total=total_steps, desc="Training") as pbar:
        for epoch in range(epochs):
            # --- Train ---
            net.train()
            indices = np.arange(n_train)
            np.random.shuffle(indices)
            batch_losses = []

            for b in range(0, n_train, batch_size):
                batch_idx = indices[b:b + batch_size]
                xb = X_train[batch_idx]
                yb = Y_train[batch_idx]

                x = torch.tensor(xb).unsqueeze(2).unsqueeze(3).float().to(device)
                y = torch.tensor(yb).long().to(device)
                target = torch.zeros((len(y), num_classes, 1, 1, 1), device=device)
                target.scatter_(1, y[:, None, None, None, None], 1.0)

                outputs = net(x)
                loss = loss_fn.numSpikes(outputs, target)

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                batch_losses.append(loss.item())
                pbar.update(1)

            # --- Adaptive delay clamping ---
            if use_delay:
                if epoch <= 250:
                    net.clamp_delays(max_delay, max_delay)
                else:
                    update1 += 1
                    update2 += 1
                    for name, param in net.named_parameters():
                        if "delay1.delay" in name and update1 > 150:
                            sorted_ = torch.sort(
                                torch.floor(param.detach().flatten())
                            )[0]
                            thea1_val = torch.max(sorted_)
                            if sorted_[108] > (thea1_val - 5):
                                thea1 = int(thea1_val.item()) + 1
                                update1 = 0
                        elif "delay2.delay" in name and update2 > 150:
                            sorted_ = torch.sort(
                                torch.floor(param.detach().flatten())
                            )[0]
                            thea2_val = torch.max(sorted_)
                            if sorted_[108] > (thea2_val - 5):
                                thea2 = int(thea2_val.item()) + 1
                                update2 = 0
                    net.clamp_delays(thea1, thea2)

            # --- Validate ---
            net.eval()
            val_loss = 0.0
            correct = 0
            total = 0
            n_val_batches = 0
            with torch.no_grad():
                for b in range(0, len(Y_val), batch_size):
                    xb = X_val[b:b + batch_size]
                    yb = Y_val[b:b + batch_size]
                    x = torch.tensor(xb).unsqueeze(2).unsqueeze(3).float().to(device)
                    y = torch.tensor(yb).long().to(device)
                    target = torch.zeros(
                        (len(y), num_classes, 1, 1, 1), device=device
                    )
                    target.scatter_(1, y[:, None, None, None, None], 1.0)

                    outputs = net(x)
                    val_loss += loss_fn.numSpikes(outputs, target).item()

                    pred = snn.predict.getClass(outputs)
                    correct += (pred.cpu() == y.cpu()).sum().item()
                    total += len(y)
                    n_val_batches += 1

            val_loss /= max(1, n_val_batches)
            val_acc = correct / max(1, total)
            train_loss = float(np.mean(batch_losses))

            delays = net.get_delays()
            avg_delay = (
                float(np.mean([np.mean(d) for d in delays.values() if len(d) > 0]))
                if delays else 0.0
            )

            log["epoch"].append(epoch)
            log["train_loss"].append(train_loss)
            log["val_loss"].append(float(val_loss))
            log["val_acc"].append(float(val_acc))
            log["delay_mean"].append(avg_delay)

            pbar.set_postfix(
                epoch=epoch + 1,
                train=f"{train_loss:.3f}",
                val=f"{val_loss:.3f}",
                acc=f"{val_acc:.2%}",
                delay=f"{avg_delay:.1f}",
            )
            scheduler.step()

            # --- Early stopping ---
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_model_state = {k: v.clone() for k, v in net.state_dict().items()}
                early_stop_counter = 0
            else:
                early_stop_counter += 1
                if early_stop_counter >= patience:
                    print(f"\nEarly stopping at epoch {epoch + 1}")
                    break

    if best_model_state is not None:
        net.load_state_dict(best_model_state)

    return net, log


# =====================================================================
# Test-set evaluation
# =====================================================================

def test_accuracy(
    net: SHDNetwork,
    X_test: np.ndarray,
    Y_test: np.ndarray,
    batch_size: int = 64,
) -> float:
    """Compute classification accuracy on a pre-perturbed test set.

    Args:
        net: Trained network.
        X_test: Perturbed test spike trains.
        Y_test: Test labels.
        batch_size: Evaluation batch size.

    Returns:
        Accuracy in [0, 1].
    """
    net.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for b in range(0, len(Y_test), batch_size):
            xb = X_test[b:b + batch_size]
            yb = Y_test[b:b + batch_size]
            x = torch.tensor(xb).unsqueeze(2).unsqueeze(3).float().to(device)
            pred = snn.predict.getClass(net(x))
            correct += int((pred.cpu().numpy() == yb).sum())
            total += len(yb)
    return correct / max(1, total)


# =====================================================================
# Sweep over input-perturbation levels
# =====================================================================

def run_variation_sweep(
    dataset_key: str,
    use_delay: bool,
) -> tuple[dict[float, dict], dict[str, dict]]:
    """Input-perturbation sweep for one (dataset_key, use_delay) variation.

    Loads the dataset, then for every f in F_VALUES regenerates the perturbed
    splits, trains a fresh model, evaluates it on the perturbed test set, and
    persists the per-variation checkpoints and JSON.

    Args:
        dataset_key: One of "norm", "part", "whole".
        use_delay: Train the SGD-delay variant if True, else SGD.

    Returns:
        Tuple of (test accuracy per f, training log per f).
    """
    input_dim = DATASET_CONFIGS[dataset_key]["input_dim"]
    mat_file = os.path.join(SCRIPT_DIR, DATASET_CONFIGS[dataset_key]["mat_file"])
    delay_tag = "delay" if use_delay else "nodelay"
    model_prefix = f"shd_{dataset_key}_{delay_tag}_inputpert"

    print(f"\n{'#' * 70}")
    print(f"# Variation: dataset={dataset_key} | delay={delay_tag}")
    print(f"# Input dim: {input_dim} | Model prefix: {model_prefix}")
    print(f"{'#' * 70}")

    data_dir = os.path.join(SCRIPT_DIR, "data")
    os.makedirs(data_dir, exist_ok=True)

    X_all, Y_all = load_shd_data(mat_file, target_T=SIM_PARAMS["tSample"])

    sweep_results: dict[float, dict] = {}
    training_logs: dict[str, dict] = {}

    for f_value in F_VALUES:
        f_value = float(f_value)
        print(f"\n===== {model_prefix} | Input perturbation f = {f_value} =====")

        print("Preprocessing dataset (perturbing input spike trains)...")
        (X_train, Y_train), (X_val, Y_val), (X_test, Y_test) = preprocess_full_dataset(
            X_all, Y_all, f_value,
            training_range=TRAIN_RANGE,
            validation_range=VAL_RANGE,
            testing_range=TEST_RANGE,
            seed=SEED,
        )
        print(f"Train: {len(Y_train)} | Val: {len(Y_val)} | Test: {len(Y_test)}")

        net, log = train_model(
            X_train, Y_train, X_val, Y_val,
            input_dim=input_dim,
            hidden_units=HIDDEN_UNITS,
            num_classes=NUM_CLASSES,
            use_delay=use_delay,
            max_delay=MAX_DELAY,
            epochs=EPOCHS,
            batch_size=BATCH_SIZE,
            lr=LEARNING_RATE,
            seed=SEED,
            patience=EARLY_STOP_PATIENCE,
        )

        acc = test_accuracy(net, X_test, Y_test, batch_size=64)
        print(f"Test accuracy at f={f_value}: {acc:.4f}")

        sweep_results[f_value] = {"accuracy": float(acc)}
        training_logs[f"f={f_value}"] = log

        model_path = os.path.join(
            data_dir, f"{model_prefix}_f{int(f_value * 10):02d}.pt"
        )
        torch.save(net.state_dict(), model_path)
        print(f"Saved model to {model_path}")

    save_results(sweep_results, training_logs, model_prefix)
    return sweep_results, training_logs


def save_results(
    sweep_results: dict[float, dict],
    training_logs: dict[str, dict],
    model_prefix: str,
) -> None:
    """Write sweep accuracies and per-f training logs to the log directory.

    Args:
        sweep_results: Test accuracy per perturbation level.
        training_logs: Per-epoch training log per perturbation level.
        model_prefix: Per-variation filename prefix.
    """
    log_dir = os.path.join(SCRIPT_DIR, "log")
    os.makedirs(log_dir, exist_ok=True)

    results_serialisable = {
        str(f_val): {"accuracy": float(data["accuracy"])}
        for f_val, data in sweep_results.items()
    }
    results_path = os.path.join(
        log_dir, f"{model_prefix}_input_perturbation_results.json"
    )
    with open(results_path, "w") as fp:
        json.dump(results_serialisable, fp, indent=2)
    print(f"Results saved to {results_path}")

    logs_serialisable = {
        f_key: {
            k: [float(v) for v in vals] if isinstance(vals, list) else vals
            for k, vals in log.items()
        }
        for f_key, log in training_logs.items()
    }
    logs_path = os.path.join(
        log_dir, f"{model_prefix}_input_perturbation_training_logs.json"
    )
    with open(logs_path, "w") as fp:
        json.dump(logs_serialisable, fp, indent=2)
    print(f"Training logs saved to {logs_path}")


# =====================================================================
# Main
# =====================================================================

def main() -> None:
    """Run the configured input-perturbation sweep(s)."""
    if TRAIN_ALL_VARIATION:
        print(f"Batch mode: training {len(ALL_VARIATIONS)} variations:")
        for dataset_key, use_delay in ALL_VARIATIONS:
            tag = "delay" if use_delay else "nodelay"
            print(f"  - shd_{dataset_key}_{tag}_inputpert")
        print(f"f sweep: {F_VALUES}")
    else:
        tag = "delay" if USE_DELAY else "nodelay"
        print(f"Dataset: SHD {DATASET_KEY} | Input dim: {INPUT_DIM}")
        print(f"Network mode: {'SGD-delay' if USE_DELAY else 'SGD (no delay)'}")
        print(f"Model prefix: shd_{DATASET_KEY}_{tag}_inputpert")
        print(f"f sweep: {F_VALUES}")

    variations_to_run = (
        ALL_VARIATIONS if TRAIN_ALL_VARIATION else [(DATASET_KEY, USE_DELAY)]
    )

    for dataset_key, use_delay in variations_to_run:
        run_variation_sweep(dataset_key, use_delay)


if __name__ == "__main__":
    main()
